"""
Django settings for knlLogistics project - SECURITY HARDENED VERSION
Updated for Render Deployment with proper security practices

Generated by 'django-admin startproject' using Django 4.0.4.

IMPORTANT: All sensitive credentials are managed via environment variables.
Never hardcode passwords or API keys in this file!

For more information on this file, see:
https://docs.djangoproject.com/en/4.0/topics/settings/
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url


# ============================================================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# ============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
# ============================================================================
# IMPORTANT: Generate a new SECRET_KEY for production!
# Run: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
# Then set it in your Render environment variables: SECRET_KEY=<generated-key>

SECRET_KEY = config('SECRET_KEY', default='dev-key-change-in-production-immediately')


# ============================================================================
# DEBUG MODE - NEVER set to True in production!
# ============================================================================
# This is automatically False on Render when SECRET_KEY is set properly

DEBUG = config('DEBUG', default=False, cast=bool)


# ============================================================================
# ALLOWED HOSTS - Specify exact domains only
# ============================================================================
# For Render, set ALLOWED_HOSTS in environment variables
# Example: ALLOWED_HOSTS=knllogistics.onrender.com,yourdomain.com,localhost,127.0.0.1

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost,knllogistics.onrender.com'
).split(',')

# Strip whitespace from each host
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS]


# ============================================================================
# APPLICATION DEFINITION
# ============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'knlInvoice',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'knlLogistics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'knlLogistics.wsgi.application'


# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# Automatically detects Render PostgreSQL or uses local SQLite
# Render sets DATABASE_URL environment variable automatically

if config('DATABASE_URL', default=None):
    # RENDER: Use PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # LOCAL DEVELOPMENT: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ============================================================================
# PASSWORD VALIDATION
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================================
# INTERNATIONALIZATION
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True

# ✅ TIMEZONE CONFIGURATION
USE_TZ = True  # Enable timezone support
TIME_ZONE = 'UTC'  # Use UTC (or 'Africa/Lagos' for Nigeria)

# ✅ DATETIME INPUT FORMATS
DATE_INPUT_FORMATS = [
    '%Y-%m-%d',      # 2025-01-12
    '%d-%m-%Y',      # 12-01-2025
    '%Y-%m-%d %H:%M:%S',  # 2025-01-12 15:30:00
]

DATETIME_INPUT_FORMATS = [
    '%Y-%m-%d %H:%M:%S',
    '%Y-%m-%d %H:%M',
    '%d-%m-%Y %H:%M:%S',
    '%d-%m-%Y %H:%M',
]

# ============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# ============================================================================
# WhiteNoise handles static files in production

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise static file storage for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')


# ============================================================================
# AUTHENTICATION & LOGIN
# ============================================================================

LOGIN_REDIRECT_URL = 'knlInvoice:dashboard'
LOGIN_URL = 'knlInvoice:login'
LOGOUT_REDIRECT_URL = 'knlInvoice:index'


# ============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================================
# CRISPY FORMS CONFIGURATION
# ============================================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# These settings enhance security in production

# Only apply strict security settings when DEBUG is False
if not DEBUG:
    # HTTPS/SSL Configuration
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Additional security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HTTP Strict Transport Security (HSTS)
    # Tells browsers to only use HTTPS for this domain
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security Policy
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ("'self'",),
    }
    
    # Session security
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Strict'
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Strict'


# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================
# All email credentials come from environment variables
# NEVER hardcode passwords or sensitive information!

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Email server settings - uses Outlook/MSN SMTP by default
EMAIL_HOST = config('EMAIL_HOST', default='smtp-mail.outlook.com')
EMAIL_PORT = int(config('EMAIL_PORT', default='587'))

# CRITICAL: These MUST be set via environment variables in Render
# No defaults for sensitive credentials!
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=None)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default=None)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default='True') == 'True'
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=None)

# If email credentials are missing in production, Django will raise an error
# This is intentional - it ensures you don't forget to set them!
if not DEBUG and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD or not DEFAULT_FROM_EMAIL):
    import warnings
    warnings.warn(
        "Email configuration incomplete! Set EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, "
        "and DEFAULT_FROM_EMAIL in your environment variables.",
        RuntimeWarning
    )


# ============================================================================
# COMPANY INFORMATION
# ============================================================================
# These are used in email templates and invoices

COMPANY_NAME = config('COMPANY_NAME', default='Kamrate Nigeria Limited')
COMPANY_PHONE = config('COMPANY_PHONE', default='')
COMPANY_ADDRESS = config('COMPANY_ADDRESS', default='')
COMPANY_EMAIL = config('COMPANY_EMAIL', default='')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='')
SITE_URL = config('SITE_URL', default='http://localhost:8000')


# ============================================================================
# ADMIN & NOTIFICATIONS
# ============================================================================
# For admin email notifications

ADMINS = [
    ('Admin', config('ADMIN_EMAIL', default='idris_a@msn.com')),
]


# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
# Enables logging to console for debugging on Render

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'knlInvoice': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)


# ============================================================================
# ENVIRONMENT-SPECIFIC SETTINGS
# ============================================================================

if DEBUG:
    # Development settings
    ALLOWED_HOSTS.extend(['*'])  # Allow all hosts in development
    
    # Use console email backend for testing
    # Emails will print to console instead of sending
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production settings (Render)
    # SSL is enforced above
    # Database uses PostgreSQL
    # Email uses SMTP
    pass
# ============================================================================
# END OF SETTINGS
# ============================================================================