# Generated by Django 4.2 on 2026-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knlInvoice', '0002_product_settings_client_clientlogo_client_taxnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='province',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='province',
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Rivers', 'Rivers'), ('Enugu', 'Enugu'), ('Oyo', 'Oyo'), ('Delta', 'Delta'), ('Bauchi', 'Bauchi'), ('Imo', 'Imo'), ('Osun', 'Osun'), ('Kebbi', 'Kebbi'), ('Katsina', 'Katsina'), ('Sokoto', 'Sokoto'), ('Cross River', 'Cross River'), ('Akwa Ibom', 'Akwa Ibom'), ('Calabar', 'Calabar'), ('Yobe', 'Yobe'), ('Gombe', 'Gombe'), ('Borno', 'Borno'), ('Zamfara', 'Zamfara'), ('Niger', 'Niger'), ('Kwara', 'Kwara'), ('Nasarawa', 'Nasarawa'), ('Plateau', 'Plateau'), ('Taraba', 'Taraba'), ('Adamawa', 'Adamawa'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Ondo', 'Ondo'), ('Abia', 'Abia'), ('Anambra', 'Anambra'), ('Ebonyi', 'Ebonyi'), ('Jigawa', 'Jigawa')], max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='state',
            field=models.CharField(blank=True, choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Kano', 'Kano')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('R', 'ZAR'), ('$', 'USD'), ('N', 'NGN')], default='N', max_length=100),
        ),
    ]
