# Generated by Django 4.2 on 2026-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knlInvoice', '0004_trip_truck_tripexpense_trip_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('€', 'EUR'), ('£', 'GBP'), ('$', 'USD'), ('₦', 'NGN')], default='₦', max_length=100),
        ),
    ]
