# Generated by Django 4.2 on 2026-01-07 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knlInvoice', '0005_alter_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.FloatField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('other', 'Other')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='number',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, default=datetime.datetime(2026, 1, 7, 14, 11, 57, 989159, tzinfo=datetime.timezone.utc), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CONTAINER_HAULAGE', 'Container Haulage'), ('VEHICLE_PARTS', 'Vehicle Parts'), ('LABOR_SERVICES', 'Labor Services'), ('INSURANCE', 'Insurance Products'), ('OPERATIONAL_CHARGES', 'Operational Charges'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='knlInvoice.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days'), ('immediate', 'Immediate')], default='14 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='state',
            field=models.CharField(blank=True, choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Rivers', 'Rivers'), ('Enugu', 'Enugu'), ('Oyo', 'Oyo'), ('Delta', 'Delta')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='knlInvoice__invoice_52920f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='knlInvoice__client__99e288_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='knlInvoice__status_cbd4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='knlInvoice__issue_d_50c771_idx'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='knlInvoice.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knlInvoice.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knlInvoice.product'),
        ),
    ]
