# Generated by Django 4.2 on 2026-01-12 10:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knlInvoice', '0006_invoiceitem_paymentrecord_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date_created'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this trip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargoDescription',
            field=models.TextField(blank=True, default='', help_text='Description of cargo being transported'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cargoWeight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 12, 10, 8, 14, 65163, tzinfo=datetime.timezone.utc), help_text='When this trip record was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Destination location e.g., Port Harcourt', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='endDate',
            field=models.DateTimeField(blank=True, help_text='Trip end date and time', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 1, 12, 10, 9, 21, 62155, tzinfo=datetime.timezone.utc), help_text='Last time this record was updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(help_text='Starting location e.g., Lagos', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='revenue',
            field=models.DecimalField(decimal_places=2, help_text='Trip revenue in Nigerian Naira', max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startDate',
            field=models.DateTimeField(blank=True, help_text='Trip start date and time', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the trip', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tripNumber',
            field=models.CharField(help_text='Unique trip identifier e.g., TRIP-001-2026', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(help_text='Vehicle assigned to this trip', on_delete=django.db.models.deletion.CASCADE, to='knlInvoice.truck'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['-date_created'], name='knlInvoice__date_cr_97a158_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', '-date_created'], name='knlInvoice__user_id_408f92_idx'),
        ),
    ]
