# Generated by Django 4.2 on 2026-01-17 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knlInvoice', '0007_alter_trip_options_trip_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('Lagos', 'Lagos'), ('Ogun', 'Ogun'), ('Abuja', 'Abuja'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Rivers', 'Rivers'), ('Enugu', 'Enugu'), ('Oyo', 'Oyo'), ('Delta', 'Delta'), ('Bauchi', 'Bauchi'), ('Imo', 'Imo'), ('Osun', 'Osun'), ('Kebbi', 'Kebbi'), ('Katsina', 'Katsina'), ('Sokoto', 'Sokoto'), ('Cross River', 'Cross River'), ('Akwa Ibom', 'Akwa Ibom'), ('Calabar', 'Calabar'), ('Yobe', 'Yobe'), ('Gombe', 'Gombe'), ('Borno', 'Borno'), ('Zamfara', 'Zamfara'), ('Niger', 'Niger'), ('Kwara', 'Kwara'), ('Nasarawa', 'Nasarawa'), ('Plateau', 'Plateau'), ('Taraba', 'Taraba'), ('Adamawa', 'Adamawa'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Ondo', 'Ondo'), ('Abia', 'Abia'), ('Anambra', 'Anambra'), ('Ebonyi', 'Ebonyi'), ('Jigawa', 'Jigawa')], max_length=100),
        ),
        migrations.CreateModel(
            name='TripInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.FloatField(default=7.5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('paymentTerms', models.CharField(choices=[('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days'), ('immediate', 'Immediate')], default='14 days', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_invoices', to='knlInvoice.client')),
                ('trip', models.OneToOneField(help_text='Trip being invoiced', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='knlInvoice.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Invoice',
                'verbose_name_plural': 'Trip Invoices',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='tripinvoice',
            index=models.Index(fields=['invoice_number'], name='knlInvoice__invoice_6f3811_idx'),
        ),
        migrations.AddIndex(
            model_name='tripinvoice',
            index=models.Index(fields=['client'], name='knlInvoice__client__23c3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='tripinvoice',
            index=models.Index(fields=['status'], name='knlInvoice__status_d46a35_idx'),
        ),
        migrations.AddIndex(
            model_name='tripinvoice',
            index=models.Index(fields=['-date_created'], name='knlInvoice__date_cr_c24c70_idx'),
        ),
    ]
