# Generated by Django 4.2 on 2026-01-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knlInvoice', '0008_alter_client_state_tripinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinvoice',
            name='paymentTerms',
        ),
        migrations.RemoveField(
            model_name='tripinvoice',
            name='trip',
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='account_name',
            field=models.CharField(default='KAMRATE NIGERIA LIMITED', max_length=200),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='account_number',
            field=models.CharField(default='0004662938', max_length=50),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='bank_name',
            field=models.CharField(default='JAIZ BANK', max_length=100),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='company_address',
            field=models.CharField(default='33, Creek Road, Ibu Boulevard, Apapa, Lagos', max_length=300),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='company_email',
            field=models.CharField(default='info@kamratelimited.com', max_length=100),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='company_name',
            field=models.CharField(default='KAMRATE NIGERIA LIMITED', max_length=200),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='company_phone',
            field=models.CharField(default='08134834928, 08026826552', max_length=100),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='company_website',
            field=models.CharField(default='www.kamratelimited.com', max_length=100),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='payment_terms',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='14 days', max_length=100),
        ),
        migrations.AddField(
            model_name='tripinvoice',
            name='tin',
            field=models.CharField(default='20727419-0001', max_length=50),
        ),
        migrations.CreateModel(
            name='TripInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaded', models.DateField()),
                ('file_reference', models.CharField(max_length=100)),
                ('container_number', models.CharField(max_length=50)),
                ('terminal', models.CharField(max_length=50)),
                ('truck_number', models.CharField(max_length=50)),
                ('container_length', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='knlInvoice.tripinvoice')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='knlInvoice.trip')),
            ],
            options={
                'ordering': ['date_loaded'],
            },
        ),
    ]
